### ISSUE TITLE
Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by andreydanil** [waifung0207/ci_bootstrap_3#1]
I pulled the latest version of you app and set it up on a LAMP stack. The home page works (html), however, every other page results in errors. The message reads - Fatal error: Can't use method return value in write context. See the screenshot for more details. Can it be a dependency issue?
![error001](https://cloud.githubusercontent.com/assets/5439988/7729495/c13ae4c8-feda-11e4-8af8-f266123562a2.JPG)

By the way... Great app. Looking forward to test it and collaborate!

**Comment by waifung0207** [comment]
Can you share your server environment? e.g. web server, PHP version, etc.

From some quick Google findings, seems the problem can be due to the usage of empty() function (which I used quite a lot) for PHP version <5.5

**Comment by andreydanil** [comment]
I've deployed your CI app on multiple web servers - LAMP and XAMPP. The PHP version on the LAMP web server was 5.4, which is not compatible. Then I tried on the XAMPP environment with PHP version  5.6.8 and everything worked. 

Maybe you can clarify the required PHP version in the README? Thanks!
