### ISSUE TITLE
Call to undefined function url_decode() in Ion_auth_model.php on line 1813

### ISSUE THREAD

**Issue by abdallahajlouni** [waifung0207/ci_bootstrap_3#103]
I got this error message:
Fatal error: Call to undefined function url_decode() in ....admin\application\third_party\ion_auth\models\Ion_auth_model.php on line 1813

There is a typing mistake, the function name is : urldecode() not url_decode().

**Comment by jhunieray** [comment]
I got the same problem.

**Comment by waifung0207** [comment]
This issue is fixed after updated to latest version of Ion Auth library. Please see commit 8ce330c850f45d948fbc987b423ccb72ec6ad96a.
