### ISSUE TITLE
Starting with copying user model

### ISSUE THREAD

**Issue by buoncri** [waifung0207/ci_bootstrap_3#11]
Hi waifung0207

I am trying starting (from admin module) with this perfect for me template. Actually i am copying User.php controller to use grocery_crud with a new table in the db, so doing that: 
(File: E:\xampp\htdocs\ci_bootstrap_3\application\modules\admin\controllers\Progetti.php)
    
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Progetti extends Admin_Controller {

	/**
	 * User Management page (e.g. CRUD operations)
	 */
	public function index()
	{
		$crud = $this->crud->generate_crud('progetti');
		//$crud->columns('role', 'email', 'first_name', 'last_name', 'active', 'created_at');

		$this->mViewData['crud_data'] = $this->crud->render();		
		$this->render('crud');
	}

![cattura di schermata 2](https://cloud.githubusercontent.com/assets/3062441/9561615/e5a3fe00-4e4c-11e5-85cc-131ec68eb9a1.png)

View and delete are right. Invoking the edit (http://localhost/ci_bootstrap_3/admin/progetti/index/edit/8) rendere the right gcrud page

![cattura di schermata 3](https://cloud.githubusercontent.com/assets/3062441/9561629/a0ef3454-4e4d-11e5-85a9-24b85f5a6828.png)

Can this be a bug of the g_crud integration ?

Thanks for you efforts in this repo :-D (and for the answer)

P.S.
The same (as up) with admin_user (crontroller using gcrud and admin_users table) give a good normal crud for admin users.

Cheers

P.S.2
It can be a specific problem with my table ... i am trying with more simple tables and it seems it's ok.

**Comment by buoncri** [comment]
The same (as up) with admin_user (crontroller using gcrud and admin_users table) give a good normal crud for admin users.

Cheers

**Comment by buoncri** [comment]
Day 2

It seems a problem with ckeditor. When i disable it, the app go ok.

**Comment by waifung0207** [comment]
Sorry for my slow response, even you closed the issue I'm still concerning the problem you had encountered and hope I can help.

The "Edit" page looks properly for me (except those mis-positioning of CKEditor buttons), and please be reminded that if you set the MySQL field as "TEXT" datatype, Grocery CRUD will recognize that and show the field CKEditor automatically. 

If you only require a simple input text field, you have two options:
1) set the field as "VARCHAR" in MySQL database
2) use Grocery CRUD's [field_type()](http://www.grocerycrud.com/documentation/options_functions/field_type) function and set the type to "string" manually

More info regarding the CKEditor settings - you can also change the text editor from this file: application/modules/admin/config/grocery_crud.php, where "grocery_crud_default_text_editor" decides which text editor to be used, and "grocery_crud_text_editor_type" decides whether to display the editor in "full" mode or "minimal" mode. 

Hope I didn't misunderstand the issue, and thanks for your feedback :)

**Comment by buoncri** [comment]
Yes, as you sad I am using the second solution, and have clear text whithout html's tags.
