### ISSUE TITLE
CSS: "icon" class conflict with AdminLTE

### ISSUE THREAD

**Issue by theoary** [waifung0207/ci_bootstrap_3#12]
The "icon" class from this css at assets/css/admin.css seem to be conflict with AdminLTE "small-box icon", makes the icon on small-box placed outside 
```
/**
 * Align custom icon fonts with FontAwesome
 */
.icon {
	display: inline-block;
	width: 20px;
}
```
Changing this class to different class-name could solved the issue

related file:
application/modules/admin/config/site.php
```
// Demo to add sections with subpages
		'demo' => array(
			'name'		=> 'Demo',
			'url'		=> 'demo',
			'icon'		=> 'icon ion-gear-b',	// use non-FontAwesome icon (with "icon" class to align styling)
			'children'  => array(
				'Pagination'	=> 'demo/pagination',
				'Sortable'		=> 'demo/sortable',
				'Item 1'		=> 'demo/item/1',
				'Item 2'		=> 'demo/item/2',
				'Item 3'		=> 'demo/item/3',
			)
		),
		// end of demo
```

**Comment by waifung0207** [comment]
Thanks for reporting.

I verify the usage of custom .icon CSS rule, and removed it since the icon on sidemenu can be set like this:
```php
'icon'      => 'ion ion-gear-b',
```

AdminLTE small-box should be displayed properly now.
