### ISSUE TITLE
How to change background color the content area ?

### ISSUE THREAD

**Issue by khompetch** [waifung0207/ci_bootstrap_3#16]
First of all, Thank you very much  for this software.
I would like to change background color the content area.
How to change background color the content area ?

Thank you very much.

![admin_user](https://cloud.githubusercontent.com/assets/14936501/10240706/cded42bc-6909-11e5-8619-1563a675fe07.png)

**Comment by waifung0207** [comment]
Hi,

You can consider one of these methods:
* Adding inline styles to the default layout (i.e. /application/modules/admin/views/_layouts/default.php), or to the specific page (e.g. /application/modules/admin/views/crud.php if you only need color change for CRUD page)
* Changing the styles from Admin Panel specific css (from /assets/css/admin.css) then run gulp task (execute command **gulp cssmin:admin**) to rebuild the minified css (into /assets/dist/admin.min.css)

Hope these help.

**Comment by khompetch** [comment]
Thank you Waifung0207 for answer.
I choose specific change for CRUD page.
I add Tag div in  /application/modules/admin/views/crud.php
It work.
Thank you very much.
![itwork](https://cloud.githubusercontent.com/assets/14936501/10388099/419e764a-6e91-11e5-890b-50d049a15be6.jpg)

![crud](https://cloud.githubusercontent.com/assets/14936501/10387988/3acc4802-6e90-11e5-988e-36464a3ad1e2.jpg)
