### ISSUE TITLE
Grocery_CRUD_MultiSearch

### ISSUE THREAD

**Issue by buoncri** [waifung0207/ci_bootstrap_3#19]
For my projects on top of ci_bootstrap_3 i am using this extension of grocerycrud (https://github.com/Akshay-Hegde/Grocery_Crud_MultiSearch).

This extension is powerfoul for searching and simple to add via your Crud (wrapper) lib by adding the library file and inserting two lines. (and replacing of one file of the flexgrid theme).

```
    // Initialize CRUD table via Grocery CRUD library
    // Reference: http://www.grocerycrud.com/
    public function generate_crud($table, $subject = '')
    {
        // create CRUD object
        $this->CI->load->library('Grocery_CRUD');
                $this->CI->load->library('Grocery_CRUD_MultiSearch'); //those
        $crud = new grocery_CRUD_MultiSearch();                    //lines 
        $crud->set_table($table);
       ..... ecc. ecc.
```

Here a simple screenshot of the results

![search_3 1](https://cloud.githubusercontent.com/assets/3062441/11300063/208e344c-8f8c-11e5-992e-bcdfe4abbf4c.png)

If you think this can be a future to add i can make a pull request. Bye ;-)

**Comment by blondie63** [comment]
Luca, posso contattarti?

**Comment by buoncri** [comment]
ma certo che si :+1:

**Comment by blondie63** [comment]
Mi dai una tua mail?

Mauro Miotello

Inviato da iPhone

**Comment by buoncri** [comment]
buoncri@libero.it

**Comment by waifung0207** [comment]
Thanks for the suggestion, I will keep it in mind and consider adding it after investigation.
