### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by dreamerworks** [waifung0207/ci_bootstrap_3#2]
Hi Waifung, 
I admire this project and forked it. 
I changed config/database.php to connect to my database and tested the code as it is today (18-jun-2015). 
The site works fine. Changing language works fine. Going to login page (or forms example), I get this error presented bellow. 

Do you have any clue on why this might be happening? Don't know if this is an issue or just me not doing something correctly.

Thank you
--- Begin of what appears on the page
Fatal error: Can't use method return value in write context in /home/my_app_path/application/controllers/Account.php on line 33

A PHP Error was encountered
Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at /home/my_app_path/application/controllers/Account.php:33)
Filename: core/Common.php
Line Number: 564
Backtrace:

A PHP Error was encountered
Severity: Compile Error
Message: Can't use method return value in write context
Filename: controllers/Account.php
Line Number: 33
Backtrace:
--- End of what appears on the page

**Comment by waifung0207** [comment]
I suspect the error is caused by redirection when doing form validation, which you can find from my Form Builder class (application/libraries/Form_builder.php > find from validate() function).

Or maybe you can share your server info (web server, php version) since some others also mentioned similar issue and their environment is using IIS server - which I am not that familiar with.

**Comment by dreamerworks** [comment]
Hi, 
thank you, I using PHP version 5.2.17 on a linux host (running apache).

**Comment by dreamerworks** [comment]
Hi, i did some digging and it seems that the problem goes away if you change 
if ( !empty($this->input->post()) &&  $form->validate() )
by 
if ( $this->input->post() &&  $form->validate() )

I tried this solution and it worked. 

According to the php docs the empty() function only works on variables, not objects.

References:
   http://stackoverflow.com/questions/16882684/empty-function-not-working-in-codeignitor
   http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context
   http://php.net/manual/en/function.empty.php

Note: there may be other uses of empty() that need to be changed on the project...

**Comment by dreamerworks** [comment]
Replaced:
application/controllers/Account.php: 3 times
application/controllers/Example.php: 1 time
application/modules/admin/controllers/Login.php: 1 time

**Comment by waifung0207** [comment]
Thanks for detailed reporting - yes I have used empty() quite a lot throughout the application, but I wonder if the PHP version matters since I don't have the issue in my hosting environment (PHP 5.5+). 

Anyway I will try to beware of the issue and fixed them when I have time. Thanks again.
