### ISSUE TITLE
Gracery crud insert/edit select field issue

### ISSUE THREAD

**Issue by gianni72** [waifung0207/ci_bootstrap_3#20]
Hello,

I've tried grocery_crud insert/edit on iOS (iPhone / iPad) and the select field won't work

Thank you

**Comment by buoncri** [comment]
try a clean grocerycrud stand-alone install ?

**Comment by waifung0207** [comment]
Hi, is the problem still exist? 

If yes, please state the iOS version and I will try to check on that. Thanks.
