### ISSUE TITLE
ReCaptcha Validation on Form submission

### ISSUE THREAD

**Issue by wpraas** [waifung0207/ci_bootstrap_3#22]
Hi,
I really like the feature of ReCaptcha but unfortunately it is not working :
Reference is given below:
ReCaptcha is not validated on forms (other forms fields are validated but recaptcha does not):
../demo/form_basic
../demo/form_bs3

Can you assist?

**Comment by filmpixel** [comment]
Hi, 

I installed ci_bootstrap_3 today, so I'm no expert, but I found that you have to register your domain with Google reCAPTCHA for the captcha to work in the demo.  Good news - it's quick and easy!

Register your domain by visiting https://www.google.com/recaptcha

Replace the demo keys with yours (reCAPTCHA will not work with demo keys)
by updating the placeholder keys in this file: \application\config\form_validation.php, lines 131-132

Placeholder keys:

<code>
$config['recaptcha'] = array(
	'site_key'		=> '6Lc1MAYTAAAAAOdhZ0qvGMUFuBD-J6fJIP3DvX-b',
	'secret_key'	=> '6Lc1MAYTAAAAAEARt-nT1En9NBonssoo4vWI12Nl',
);
</code>

Once you replace the demo keys with your own, the validation should work.

/T

**Comment by waifung0207** [comment]
Thanks filmpixel for the help on replying this issue; yes I believe the problem is due to domain binding to Google reCAPTCHA, since the preset one is for "localhost" only.

Please let me know if you have further question on this. Thanks.
