### ISSUE TITLE
Please add KCFinder integration on CKEditor

### ISSUE THREAD

**Issue by dhanangpr** [waifung0207/ci_bootstrap_3#3]
Hi Waifung,please add KCFinder integration on CKEditor, CI3 session is different from CI2, so it's hard to call session to limit the authorized access only in KCFinder. Thanks

**Comment by waifung0207** [comment]
Do you mean the CKEditor when using GroceryCRUD library?

If yes then you will need to raise an issue on its Github page, as the library is not maintained by myself.
https://github.com/scoumbourdis/grocery-crud/

**Comment by dhanangpr** [comment]
Yes, ok.
