### ISSUE TITLE
group user level

### ISSUE THREAD

**Issue by blutsauger** [waifung0207/ci_bootstrap_3#36]
i try to create a new group from database, then i create a new user with that group.
but when i'm try login. 
it seems that the user that using that group level not worked and cannot login. 

how i can add a new group login. that can login??

**Comment by boloindia** [comment]
here is a catch. You need to add the group in site.php upnder application\modules\admin\config.
![image](https://cloud.githubusercontent.com/assets/5237140/12089924/d8a1acfc-b30f-11e5-97b3-0d8c80176df7.png)

**Comment by waifung0207** [comment]
Sorry for late reply. 

I have actually considered the user group handling many times, and recently the repo was updated with different coding to manage users. 

Please pull the repo and enter Admin Panel again (with /sql/latest.sql re-import), then you should see the new "Users" and "Admin Panel" options on sidemenu.

To change the AdminLTE skins of each group, the method is similar to what @boloindia said (thanks dude for helping to reply :)), but /config/site.php is now like:
```php
	'adminlte' => array(
		'webmaster'	=> array('skin' => 'skin-red'),
		'admin'		=> array('skin' => 'skin-purple'),
		'manager'	=> array('skin' => 'skin-black'),
		'staff'		=> array('skin' => 'skin-blue')
	),
```
