### ISSUE TITLE
Litel eror: No input file specified.

### ISSUE THREAD

**Issue by Bucur** [waifung0207/ci_bootstrap_3#37]
I give a small error when I login: No Specified input file. I need help...

**Comment by driftypuddle** [comment]
go to htaccess and add ? to idex.php at bottom so it RewriteRule ^(.*)$ index.php?/$1 [L]

**Comment by waifung0207** [comment]
Thanks @driftypuddle for helping to reply.

I have to say I'm not expert on setting .htaccess... but a screenshot and list out server environment (e.g. PHP version, did you enable Apache rewrite module, etc.) will be nice to help me figure out the issue.

Please let me know if the problem still exists. Thanks.
