### ISSUE TITLE
comment module

### ISSUE THREAD

**Issue by mrjagiring** [waifung0207/ci_bootstrap_3#38]
as you perform blog module, do you intent to create comment module?
or if you have any reference, could you share with us?

thanks

ps: I love your work, great!!

**Comment by waifung0207** [comment]
Sorry currently I don't have plan to include blog comment feature in this repo, since the blogging part is just for demonstration purpose right now (instead of practical use).

Perhaps you can check out [Disqus](https://disqus.com/) which should be easy to integrate into pages.
