### ISSUE TITLE
Handling subdomains with HMVC

### ISSUE THREAD

**Issue by dschallert** [waifung0207/ci_bootstrap_3#4]
What is the recommended approach to work with subdomains instead of subdirectories?

Thanks in advance

**Comment by waifung0207** [comment]
CodeIgniter does not support subdomain routing natively (which I think quite essential for a router) at this moment, so it seems that is no "elegant" way to handle them. 

However you may set some custom logic inside config file like this reference: http://elanmarikit.me/2011/03/codeigniter-mapping-routing-subdomain.html

The author suggested to put into config.php (maybe for older CI version), however I would rather save them into routes.php instead. 

Hope this helps.

**Comment by dschallert** [comment]
Thank you very much for the advanced info.  I'm aware of that routes.php method and i used that in other projects already. The idea that came up to my mind basically was to have each application stored under /application/modules/ path but running them on separate subdomains and as seperated applications. With this approach the applications could have been sharing custom libraries, even when they are running on different sudomains.

We're going to develop a SaaS application which will have multiple frontends and backens which will run on serveral subdomains:

* Admin Backend (admin.xyz.com):
- Backend to manage all sellers
- Utilizes a database for all authentification purposes & seller management [db_app_core]

* Seller Backend (backoffice.xyz.com):
- Backend for sellers where they can manage their products
- Utilizes the [db_app_core] for authentification and accounting
- Each seller has its own database and schema [db_seller_xyz]

* Buyer Frontend (frontend.xyz.com):
- Frontend where buyers can buy stuff
- Utilizes the according sellers db schema depending on a ?seller-id=  GET parameter

Anyways I've come to the conclusion that it is probably better to have multiple and independet CI instances or atleast independent applications for each purpose and subdomain. The subdomain routing should also be handled by the webserver/nginx instead of having a wildcard in the vhost and matching them in PHP --> probably huge performance bottleneck.

In terms of scalability there anyways will be the demand of having each individual application running on different nodes in the future. Therfor this is another argument for keeping them seperated and independant.

Thanks in advance
Dominic
