### ISSUE TITLE
i got error when open demo cover photos

### ISSUE THREAD

**Issue by albertz-chaniago** [waifung0207/ci_bootstrap_3#41]
Message: Methods with the same name as their class will not be constructors in a future version of PHP; Image_moo has a deprecated constructor

Filename: libraries/Image_moo.php

Line Number: 69
Backtrace:

File: C:\Program Files (x86)\Ampps\www\ci_admin\application\third_party\MX\Modules.php
Line: 157
Function: _error_handler

File: C:\Program Files (x86)\Ampps\www\ci_admin\application\third_party\MX\Modules.php
Line: 157
Function: include_once

File: C:\Program Files (x86)\Ampps\www\ci_admin\application\third_party\MX\Loader.php
Line: 177
Function: load_file

File: C:\Program Files (x86)\Ampps\www\ci_admin\application\modules\admin\libraries\Image_crud.php
Line: 493
Function: library

File: C:\Program Files (x86)\Ampps\www\ci_admin\application\core\controllers\Admin_Controller.php
Line: 132
Function: render

File: C:\Program Files (x86)\Ampps\www\ci_admin\application\modules\admin\controllers\Demo.php
Line: 82
Function: render_crud

File: C:\Program Files (x86)\Ampps\www\ci_admin\index.php
Line: 292
Function: require_once

**Comment by waifung0207** [comment]
Hi,

Are you using PHP7? This repo is not tested on it so probably there will be issues.

**Comment by albertz-chaniago** [comment]
yes iam using php 7

**Comment by waifung0207** [comment]
As I seen from the error message and from [this article](http://php.net/manual/en/migration70.deprecated.php), you can try to edit the file directly as temporary solution: /application/modules/admin/libraries/Image_moo.php (which is a dependency of Image CRUD library).

See if it works after changing line 93 from:
```php
function Image_moo()
```
to 
```php
function __construct()
```

**Comment by albertz-chaniago** [comment]
thank you,probrem solved.

**Comment by if313103** [comment]
Hyy waifung0207 i have the same error with albert but nothing happend after i do what do say. can you help me?

**Comment by waifung0207** [comment]
Hi if313103, can you copy the error message so I can check with it?

**Comment by if313103** [comment]
i just download project image gallery grocerry CRUD from (http://waryantosite.blogspot.co.id/2013/10/membuat-galeri-foto-dengan-codeigniter.html)
and i try to execute application in my PC but when i try to upload image in Example1 i go terror like this :

A PHP Error was encountered

Severity: 8192

Message: Methods with the same name as their class will not be constructors in a future version of PHP; Image_moo has a deprecated constructor

Filename: libraries/image_moo.php

Line Number: 69

Can you help me waifung0207 ?

**Comment by waifung0207** [comment]
Please just follow my suggested solution from above, I have answered albertz-chaniago already.
