### ISSUE TITLE
embedded scripts position

### ISSUE THREAD

**Issue by webacers** [waifung0207/ci_bootstrap_3#44]
Is there any way to handle embedded scripts like this as it was handled previously?
<?php $this->start('scripts_foot'); ?>
//
<?php

**Comment by waifung0207** [comment]
Unfortunately I have removed the [Plates template](http://platesphp.com/) recently, to make the repo more closer to CodeIgniter style (and avoid developer to learn new stuff unnecessarily).

However I have implemented some logic to maintain the flexibility when embed scripts & stylesheets.

To embed scripts / stylesheets globally, you can update config/site.php and put the files under 'scripts' or 'stylesheets'.

To embed scripts / stylesheets on separate pages, you can make use of **add_script()** and **add_stylesheet()** functions to append or prepend the files. 

For example, you may code like this in a controller:
```php
public function index()
{
	$this->add_script('assets/js/custom_script.js');
	$this->render('home');
}
```

**Comment by mastercho** [comment]
add_script() and add_stylesheet() functions is still working?

**Comment by waifung0207** [comment]
@mastercho yes they should still work, you can find them from MY_Controller file
