### ISSUE TITLE
Problems executing Gulp

### ISSUE THREAD

**Issue by tato469** [waifung0207/ci_bootstrap_3#45]
I installled everything with npm. 
Seems that everything works fine but when I execute `gulp`. The gulp script "clean" the dist folder but doesn't add the new .js/.css/fonts. I tried to revise the `gulpfile.js` but I can't see anything. :(

**Comment by waifung0207** [comment]
As you see from the /gulpfile.js/tasks/ folder, there are many small tasks to do different things

For examples:
- default: to call "build" and "watch" tasks
- build: to call "clean" then "copy", "images", "cssmin", "uglify"

When you execute `gulp` command, the "default" task will be executed and "clean" the dist folder at first step, but if you found other tasks (e.g. "copy" will duplicate some files into dist) got interrupted afterwards, please check if you see any errors from terminal, and make sure the dist folder is writable.
