### ISSUE TITLE
Problem with controllers when I upload to the server.

### ISSUE THREAD

**Issue by tato469** [waifung0207/ci_bootstrap_3#46]
Once uploaded my web to the server seems that calls to controllers returns 404. 
So there is maybe .htaccess wrong?

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php/$1 [L]

**Comment by tato469** [comment]
I finally used and worked for me :+1: the following .htaccess 

In server (http://www.asddomain.com):

    RewriteEngine on
    RewriteBase /
    RewriteCond $1 !^(index.php|resources|robots.txt)
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php/$1 [L,QSA]

In local (http://localhost/myWeb) :

    RewriteEngine on
    RewriteBase /myWeb
    RewriteCond $1 !^(index.php|resources|robots.txt)
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php/$1 [L,QSA]

**Comment by r4z01** [comment]
I'm having a bad time trying to install my project on a subdirectoy on the prod server I used your htaccess  with some changes: 
`RewriteEngine on
RewriteBase /mysubfolder
RewriteCond $1 !^(index.php|resources|robots.txt)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ mysubfodler/index.php/$1 [L,QSA]`

But it didn't work, any help will be appreciated

**Comment by tato469** [comment]
Hello, try with:

`RewriteEngine on
RewriteBase /mysubfolder/
RewriteCond $1 !^(index.php|resources|robots.txt)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L,QSA]`

**Comment by hinikunj** [comment]
Hey @tato469 

I've server with instance :8081  for example http://dev.road2xtech.com:8081/mydirectory. 

i've tried above both solution in htaccess but still facing 404 without index.php

Thanks.
