### ISSUE TITLE
frontend.css

### ISSUE THREAD

**Issue by xaoranx03** [waifung0207/ci_bootstrap_3#47]
Hi, I don't know if this resolve or not issue but when I'm trying to edit frontend.css nothings happen to front end specially in home page. I try to configured out but I can't, would you please help me?

thanks.

By the way thanks for this work.

**Comment by xaoranx03** [comment]
it's already solve sorry for this...

**Comment by kiplo91** [comment]
how do u solve it? im having the same problem
