### ISSUE TITLE
Role based page auth

### ISSUE THREAD

**Issue by cansanet** [waifung0207/ci_bootstrap_3#49]
dear @waifung0207 Role based page auth works on admin side very well but I couldnt make it work on front end. For example, I want to add an /account link on frontend but I want to hide if from non-logged in users. Is there something missing on frontend side related this issue.

**Comment by Dave-robinson** [comment]
Try if  verify_auth(' // your group ') { // code to run } else { header( 'Location: http://www.yoursite.com/home' ); }

**Comment by cansanet** [comment]
thank you i wil try this

**Comment by waifung0207** [comment]
Thanks Dave for help on replying this issue.

$this->verify_auth() is one of the methods to limit page access, and in latest repo, you may also try editing **page_auth** array from site.php (usable for both Frontend Website and Admin Panel) to enable specific groups of users for different pages.
