### ISSUE TITLE
Error on creating user

### ISSUE THREAD

**Issue by dreamerworks** [waifung0207/ci_bootstrap_3#5]
When creating first user I got an error. 
Placing this:
```php
    if ($query && $query->num_rows() > 0) {
    	return $query->row();
    }
    return false;
```
instead of this:
```php
    return $query->num_rows()->row();
```
on application/core/MY_Model.php in function "get_by($where, $joins = array())" solved the problem.

Note: Mandrill integration is working fine :)

**Comment by waifung0207** [comment]
Thanks for reporting, I have pushed a commit which should fix the issue.
