### ISSUE TITLE
PHP 5.4 or Greater

### ISSUE THREAD

**Issue by poing** [waifung0207/ci_bootstrap_3#51]
Because you use the short array syntax ```[]```, your code will **only** work on PHP 5.4 or greater. Sadly, that means I can't use it. 

 _Bleading edge, means one less user_

**Comment by waifung0207** [comment]
I remember I have checked my code on this issue but maybe some of them is still using the short array syntax. If you found any of them, pull requests are welcomed and I will appreciate much on that. 

Anyway, PHP 5.4+ is not really a new version (>5 years ago), and is also recommended by CodeIgniter official ([reference link here](https://www.codeigniter.com/user_guide/general/requirements.html)), so when possible I would suggest you to upgrade PHP version too - but I understand for many shared hosted servers are still using older version which causes the limitation as you stated. 

Thanks for the issue.

**Comment by uaktags** [comment]
http://php.net/supported-versions.php
Please do NOT add support for anything below 5.5. 
I've yet to find a shared hosting provider that doesn't give the option to move to higher versions of PHP. If a provider doesn't push security updates and has outdated versions, i'd question their business.
