### ISSUE TITLE
integration with sendgrid? 

### ISSUE THREAD

**Issue by prexyx** [waifung0207/ci_bootstrap_3#53]
first of all thanks for putting up this amazing set of tools together..

i was trying to integrate sendgrid rather than mailgun but couldn't make it work.
Is it possible to use email client for sending emails via sendgrid smtp or even web api?

**Comment by waifung0207** [comment]
You may try one of these methods:

1. Send via SendGrid HTTP API: you may have a look in my custom Email Client library (/application/libraries/Email_client.php) and add the "sendgrid" platform as you wish; you will need to add the [SendGrid PHP library](https://github.com/sendgrid/sendgrid-php) by composer as well. 

2. Send via SendGrid SMTP: you may use traditional email setup (as seen from CodeIgniter official doc [here](http://www.codeigniter.com/user_guide/libraries/email.html)) and update the values from /application/config/email.php.
