### ISSUE TITLE
MY_Form_validation callbacks are not working with HMVC

### ISSUE THREAD

**Issue by jromero-onclick** [waifung0207/ci_bootstrap_3#55]
In order to make the callbacks work inside a module, MY_Form_validation should have a public property $CI and then add a reference to the controller after loading the form_validation library, just as wiredesignz explained in the documentation:

https://bitbucket.org/wiredesignz/codeigniter-modular-extensions-hmvc

```php
<?php
/** application/libraries/MY_Form_validation **/ 
class MY_Form_validation extends CI_Form_validation 
{
    public $CI; // make the CI_Form_validation::CI property public
}
```

```php
<?php
class Xyz extends MX_Controller 
{
    function __construct()
    {
        parent::__construct();

        $this->load->library('form_validation');
        $this->form_validation->CI =& $this;
    }
}
```

**Comment by jromero-onclick** [comment]
Also remember to move the file to the appropiated folder:

https://github.com/waifung0207/ci_bootstrap_3/issues/54

**Comment by waifung0207** [comment]
Thanks for the issue, I will have a look and update in next version.
