### ISSUE TITLE
body class hold transition

### ISSUE THREAD

**Issue by picepice** [waifung0207/ci_bootstrap_3#63]
First of all thank you for making this nice project. I have an issue on changing the body class..

in the head.php `<body class="<?php echo $body_class; ?>">` i cant find where do i change it.. i want something like` <body class="hold-transition skin-blue sidebar-mini">`

**Comment by waifung0207** [comment]
You can either:
1. update $this->mBodyClass variable from controller (referenced from /application/core/MY_Controller)
2. update /application/views/_base/head.php and change the body class directly; but remember all pages will be affected by this method

**Comment by picepice** [comment]
thank you for the reply..
