### ISSUE TITLE
Bug: Admin Panel opens after logging in as member

### ISSUE THREAD

**Issue by codestellar** [waifung0207/ci_bootstrap_3#66]
Hi @waifung0207 
I faced a critical security issue in the application.

- Logged in as Webmaster

- Logged Out

- Logged in as member@member.com

- Opened Admin Panel by typing in the URL directly

- Admin Panel opens

**Comment by buoncri** [comment]
try to look at issue #64

**Comment by waifung0207** [comment]
Move discussion to #64 and closing this issue.
