### ISSUE TITLE
Error Creating User when production mode is on

### ISSUE THREAD

**Issue by spaznuski** [waifung0207/ci_bootstrap_3#7]
Hi,
Love the work you are doing with this project so far, I have one error when production mode is enabled and trying to create a user. after submit on the the signup page I get the error below. You will not see the issue in development mode because the ReCaptcha check is skipped. Is there a library I am missing?
Fatal error: Class 'ReCaptcha\ReCaptcha' not found in application/libraries/Form_builder.php on line 412

**Comment by waifung0207** [comment]
Yes you will need enter the application folder, then execute command ```composer install``` to install required packages. 

If Composer is not installed yet, please follow the Getting Started page from its official website: https://getcomposer.org/
