### ISSUE TITLE
Can I use this for production?

### ISSUE THREAD

**Issue by laupkram** [waifung0207/ci_bootstrap_3#76]
Can I use this for production? If not what are those parts missing yet to make this production ready? I hope I can lend a help.

**Comment by Dave-robinson** [comment]
Yes this is a highly modular codeigniter website. You can do CRUD database queries, api calls, their are several php packages included to use for mail etc, gulp, i think composer and so much more. I use it and am currently developing a custom database management software and i'm using this as a foundation - Its taught me a lot ! Good security with password retry checking, login time recording, password recovery & encryption. Its many projects pulled together in a brilliant fashion. And regarding what parts are missing, its really up to you to use the tools provided to build your site and add-on what you need .... Good luck !

**Comment by laupkram** [comment]
Thank you for the feedback :)

**Comment by Dave-robinson** [comment]
No problems, I have learnt a lot from looking at waifung0207's code. Its great if  using components over again - i.e in the admin section - \modules\adminlte\controllers  there are some awesome widgets and it gave me the understanding to repeat the process and adapt it to display data without endless writing. I am certainly no expert but this is very well laid out !
