### ISSUE TITLE
Class 'League\Plates\Engine' not found

### ISSUE THREAD

**Issue by wirjoadmodjo** [waifung0207/ci_bootstrap_3#9]
after i install this framework, i have an error, "Class 'League\Plates\Engine' not found"
what should i do?

thanks before, sorry for my bad english.

**Comment by waifung0207** [comment]
You can follow procedure like these:

1. Install Composer: https://getcomposer.org/ (from Getting Started page)
2. Use terminal to enter /application/ folder, then type command: composer install
3. Wait until all packages to be downloaded into /application/vendor/ folder, then you should be able to start the page successfully

Sorry I am still working on this repo and made a lot of breaking changes recently, in future I will describe the setup procedure more clearly to avoid confusion from developers.

**Comment by wirjoadmodjo** [comment]
can i use this framework without using composer?

**Comment by waifung0207** [comment]
I have pushed a commit with the application/vendor/ folder added, see if you can get the site running now.
